### ISSUE TITLE
Language accent

### ISSUE THREAD

**Issue by JeevithaSelvaraj** [watson-developer-cloud/car-dashboard#27]
Hi,
 The text to speech is working very well.But the speech is not recognized properly.As we say something it takes something.Help us to rectify this issue.

Thanks in Advance

**Comment by ashleylord8** [comment]
@JeevithaSelvaraj do you think you can explain the issue a bit more in detail? I'm not exactly sure what the issue is with, "as we say something it takes something." Was there a certain phrase it didn't understand? If so, what was the phrase and what was Watson's response? Also, could you explain the title of the issue as well?

Hopefully with a little clarification I will be able to detect the issue and implement a fix. Thank you for your time!

**Comment by JeevithaSelvaraj** [comment]
@ashleylord8  Thank you for the reply.
The issue is that it is not recognizing the voice properly.For example if we speak"**_When will the rain end_**?" it takes it as "_**they've been that way and**_"...
![image](https://cloud.githubusercontent.com/assets/19709014/17724508/9eb1ca2e-6410-11e6-8ddb-6f6dba6118c6.png)

**Comment by dgterry** [comment]
@JeevithaSelvaraj Thanks very much for letting us know about the problem you are experiencing. We are always looking to improve the Watson services and are actively in discussions with the speech to text (STT) team about how we could improve this application.  If we make any updates to how we are using STT I will update this issue.  Until then you may wish to participate in the forums related to STT that can be found here: https://developer.ibm.com/answers/topics/speech-to-text/
