### ISSUE TITLE
Error 404

### ISSUE THREAD

**Issue by gyleodhis** [watson-developer-cloud/car-dashboard#63]
I have deployed this app both locally and in bluemix in both cases I get:
{"code":404,"error":"Not Found"}

Any Idea how I can fix this?

**Comment by mitchmason** [comment]
At what step do you get this?

**Comment by prateekroopra** [comment]
Right after deploying. Deploying fails actually. Even if I try via Deploy to Bluemix button.

**Comment by germanattanasio** [comment]
@stevenpkg ^^

**Comment by stevenpkg** [comment]
Can you provide commands you are using and any errors given

**Comment by germanattanasio** [comment]
@prateekroopra that's is normal. it could be related to you loading a URL that doesn't exist

**Comment by prateekroopra** [comment]
Dear German Attanasio, I raised this issue back in April! After that the
issue has been solved and I've completed the work I was hoping to since May.

Regards
Prateek

On Jun 18, 2017 5:46 PM, "German Attanasio" <notifications@github.com>
wrote:

@prateekroopra <https://github.com/prateekroopra> that's is normal. it
could be related to you loading a URL that doesn't exist

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/watson-developer-cloud/car-dashboard/issues/63#issuecomment-309274167>,
or mute the thread
